logging:
  file:
    name: cx-flow.log
#  level:
#    com:
#      checkmarx:
#        flow:
#          cmd: TRACE
#          service: TRACE
#          controller: TRACE
#    org:
#      apache:
#        http:
#          wire: TRACE
#      springframework:
#        web:
#          client:
#            RestTemplate: TRACE

cx-flow:
  bug-tracker: WAIT
  bug-tracker-impl:

checkmarx:
  username: user@cx
  password: XXX
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: https://localhost
  url: ${checkmarx.base-url}/cxrestapi
  multi-tenant: false
  incremental: false
  scan-preset: All
  configuration: Default Configuration
  team: \CxServer\SP\Company\Users
  scan-timeout: 120
#WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  #exclude-files:
  #exclude-folders:

github:
  token: XXX
  url: https://github.com
  api-url: https://api.github.com/repos/
  